name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Build the Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: user/app:${{ github.sha }}
    # - name: Install Docker Compose
    #   run: |
    #     sudo apt-get update
    #     sudo apt-get install -y docker-compose
    # - name: Start the Docker Compose stack
    #   run: |
    #     docker-compose up -d
    # - name: Stop the Docker Compose stack
    #   run: |
    #     docker-compose down


  
