name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Docker composer
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

  
