name: CI

on: pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Install Docker composer
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: Start Docker Compose
      env:
        WEB_PORT: ${{ secrets.WEB_PORT }}
        DB_NAME: ${{ secrets.DB_NAME }}
        DB_USER: ${{ secrets.DB_USER }}
        DB_PASS=: ${{ secrets.DB_PASS }}
        DB_PORT: ${{ secrets.DB_PORT }}
        
        PMA_USER: ${{ secrets.PMA_USER }}
        PMA_PASS: ${{ secrets.PMA_PASS }}
        PMA_PORT: ${{ secrets.PMA_PORT }}

        DB_TEST_NAME: ${{ secrets.DB_TEST_NAME }}
        DB_TEST_USER: ${{ secrets.DB_TEST_USER }}
        DB_TEST_PASS: ${{ secrets.DB_TEST_PASS }}
        DB_TEST_PORT: ${{ secrets.DB_TEST_PORT }}

        PMA_TEST_USER: ${{ secrets.PMA_TEST_USER }}
        PMA_TEST_PASS: ${{ secrets.PMA_TEST_PASS }}
        PMA_TEST_PORT: ${{ secrets.PMA_TEST_PORT }}

      run: |
        docker-compose up -d
    # ここまでパス
    - name: Stop the Docker Compose stack
      run: |
        docker-compose down

  
