name: CK

on: pull_request

jobs:
  job_1:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      
      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: 7.4
          extensions: intl
          coverage: none
      
      - name: Setup MySQL
        run: mysql -u root -p root -e 'CREATE DATABASE test;'
      
      - run: ls -l

